[package]
name = "rustle_code_red"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_estree_ast = "0.17.4"
lazy_static = "1.4.0"