[package]
name = "rustle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.6.0"

serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"

swc = "0.231.4"
swc_ecma_ast = "0.94.4"
swc_ecma_parser = "0.122.5"
swc_ecma_codegen = "0.127.7"
swc_common = "0.29.4"