[package]
name = "rustle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustle_locate_character = { path = "../rustle_locate_character", version = "0.1.0" }

lazy_static = "1.4.0"
regex = "1.6.0"
strum = "0.24.1"
strum_macros = "0.24.3"
magic_string = "0.3.4"
map-macro = "0.2.4"

swc_ecma_ast = "0.91.2"
swc_ecma_parser = "0.119.5"
swc_estree_ast = "0.18.2"
swc_css = "0.125.3"
swc_common = { version = "0.28.2", features = [ "tty-emitter" ] }