[package]
name = "rustle"
version = "0.1.2"
authors = ["pintariching", "qwertydelle", "linrium", "iceghost", "linh-1", "TheMixu"]
license = "MIT"
description = "The Svelte compiler, rewritten in Rust."
readme = "../README.md"
homepage = "https://github.com/pintariching/rustle"
repository = "https://github.com/pintariching/rustle"
keywords = ["svelte", "rust", "compiler", "cli"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.6.0"

serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"

swc = "0.232.68"
swc_ecma_ast = "0.94.17"
swc_ecma_parser = "0.122.23"
swc_ecma_codegen = "0.127.28"
swc_common = "0.29.13"